title: "[Idea]: "
labels: ["idea"]
body: |
  ## Feature Idea

  **What problem would this solve?**
  Describe the problem or use case.

  **Proposed Solution**
  How would you like this to work?

  **Alternatives Considered**
  What other solutions have you thought about?

  **Privacy Considerations**
  How does this align with privacy-first principles?

  **Additional Context**
  Any other relevant information, mockups, or examples.
