name: Bug Report
description: Report a bug or issue
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below.

  - type: dropdown
    id: product
    attributes:
      label: Product
      description: Which Yooz product is this bug related to?
      options:
        - Yooz Notes
        - Yooz Keyboard
        - Documentation/Website
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: What environment are you using?
      placeholder: |
        - OS: [e.g., iOS 17, Android 14, macOS 15]
        - Browser: [if web app]
        - App Version: [if applicable]
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information about the problem
      placeholder: Any additional details that might help

  - type: checkboxes
    id: terms
    attributes:
      label: Privacy Notice
      description: By submitting this issue, you confirm that you have not included any sensitive personal information
      options:
        - label: I confirm this report does not contain sensitive information
          required: true
