name: Documentation Improvement
description: Suggest improvements to documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: type
    attributes:
      label: Type of Issue
      description: What kind of documentation issue is this?
      options:
        - Typo or grammar
        - Unclear explanation
        - Missing information
        - Incorrect information
        - New documentation needed
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is this documentation issue?
      placeholder: |
        - File: README.md
        - Section: "Getting Started"
        - Link: https://...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: What's the Problem?
      description: Describe the documentation issue
      placeholder: What needs to be fixed or improved?
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Fix
      description: How would you improve this? (optional)
      placeholder: Your suggestion for improvement

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
